// Spanish UI strings. Key = the English text used in the code.
// Missing keys fall back to English, so new screens can ship first and
// get translated after. Keep keys EXACTLY equal to the English source.
export const es: Record<string, string> = {
  " by {v0}": " para {v0}",
  " · by {v0}": " · para {v0}",
  " · until {v0}": " · hasta {v0}",
  " · ~{v0} interest from here": " · ~{v0} de intereses desde hoy",
  "%/yr": "%/año",
  "({n} payments of {amt})": "({n} pagos de {amt})",
  "+ Add": "+ Agregar",
  "+ Category": "+ Categoría",
  "+ New": "+ Nueva",
  "+ Recurring expense": "+ Gasto recurrente",
  "+ Recurring income": "+ Ingreso recurrente",
  "+ add": "+ agregar",
  "+ add debt": "+ agregar deuda",
  "+ add investment": "+ agregar inversión",
  "+ add line": "+ agregar línea",
  "+ another category": "+ otra categoría",
  "+ categories inside (make it a group)": "+ categorías dentro (hazla un grupo)",
  "+ line item": "+ línea",
  "+ line items below": "+ líneas abajo",
  "+{amt} this month": "+{amt} este mes",
  "/mo": "/mes",
  "A couple of minutes to get your income, bills, debts, investments and a goal in — then your whole month plans itself. Skip anything and add it later.": "Un par de minutos para poner tus ingresos, cuentas, deudas, inversiones y una meta — y tu mes se planea solo. Puedes saltar cualquier paso y agregarlo después.",
  "A feature you want, something confusing, anything…": "Algo que quieras, algo confuso, lo que sea…",
  "A house, a car, a trip. I'll show you exactly what each paycheck needs to give.": "Una casa, un carro, un viaje. Te muestro exactamente cuánto debe aportar cada cheque.",
  "A house, a car, a watch, a trip — set a target and a date and I'll tell you exactly what each paycheck needs to give.": "Una casa, un carro, un reloj, un viaje — pon una cantidad y una fecha y te digo exactamente cuánto debe aportar cada cheque.",
  "A plan for this month only — doesn't repeat": "Un plan solo para este mes — no se repite",
  "A planning estimate, not tax advice. Many self-employed people set aside 25–30% (income tax + 15.3% self-employment tax). Confirm your rate with a tax professional.": "Es un estimado para planear, no asesoría fiscal. Muchos trabajadores independientes apartan 25–30% (impuesto sobre la renta + 15.3% de self-employment tax). Confirma tu tasa con un profesional de impuestos.",
  "APR": "Tasa anual (APR)",
  "About": "Acerca de",
  "Account": "Cuenta",
  "Active": "Activas",
  "Active subscriptions": "Suscripciones activas",
  "Add": "Agregar",
  "Add a card or loan — balance, rate and payment — and I'll tell you exactly when it dies.": "Agrega una tarjeta o préstamo — saldo, tasa y pago — y te digo exactamente cuándo lo terminas de pagar.",
  "Add a debt": "Agregar una deuda",
  "Add account": "Agregar cuenta",
  "Add an investment": "Agregar una inversión",
  "Add debt": "Agregar deuda",
  "Add expense": "Agregar gasto",
  "Add income": "Agregar ingreso",
  "Add investment": "Agregar inversión",
  "Add to plan": "Agregar al plan",
  "Add to {v0}": "Agregar a {v0}",
  "Add what falls under": "Agrega lo que va dentro de",
  "Add where your money comes from — an employer, your business, rentals — then the pieces inside it (Salary, Bonus, PTO…). Each one is tracked on its own.": "Agrega de dónde viene tu dinero — un empleador, tu negocio, rentas — y luego las partes de cada uno (Salario, Bono, PTO…). Cada una se sigue por separado.",
  "Add your recurring income (salary, rents) and expenses (rent, insurance, subscriptions) and I'll project the next 12 months for you.": "Agrega tus ingresos recurrentes (salario, rentas) y gastos (renta, seguros, suscripciones) y te proyecto los próximos 12 meses.",
  "Added to your plan": "Agregado a tu plan",
  "All": "Todo",
  "All activity →": "Toda la actividad →",
  "All together": "Todo junto",
  "All →": "Todo →",
  "Already saved — optional": "Ya ahorrado — opcional",
  "Amount": "Monto",
  "Amount + fee is added to your personal budget under Remittances.": "El monto + la comisión se suman a tu presupuesto personal en Remesas.",
  "Amount sent (USD)": "Monto enviado (USD)",
  "Amount — optional. With an amount, completing the task records it and updates your budget.": "Monto — opcional. Con monto, al completar la tarea se registra y actualiza tu presupuesto.",
  "Analyze this month": "Analizar este mes",
  "Archive": "Archivar",
  "Archive account": "Archivar cuenta",
  "Archive debt": "Archivar deuda",
  "Archive goal": "Archivar meta",
  "Ask": "Preguntar",
  "Ask about your money…": "Pregunta sobre tu dinero…",
  "Ask me anything about your money this month.": "Pregúntame lo que sea sobre tu dinero este mes.",
  "At {v0}%/yr, ~{v1} by end of December (before new contributions).": "Al {v0}%/año, ~{v1} para fin de diciembre (sin contar nuevos aportes).",
  "Back to Home": "Volver al inicio",
  "Balance · APR% · monthly payment · due day": "Saldo · tasa % · pago mensual · día de pago",
  "Balance · expected return% · monthly deposit (optional)": "Saldo · rendimiento esperado % · depósito mensual (opcional)",
  "Bank": "Banco",
  "Bank connections": "Conexiones bancarias",
  "Best": "Mejor",
  "Best option delivers {diff} {cur} more than the most expensive.": "La mejor opción entrega {diff} {cur} más que la más cara.",
  "Bills coming": "Cuentas por pagar",
  "Bonus": "Bono",
  "Breakdown ▾": "Desglose ▾",
  "Brokerage, retirement, crypto, a house fund. Add a monthly contribution if you put money in regularly. Skip if none.": "Bolsa, retiro, cripto, un fondo para casa. Agrega un aporte mensual si metes dinero seguido. Sáltalo si no tienes.",
  "Business": "Negocio",
  "Business name": "Nombre del negocio",
  "Business settings": "Ajustes del negocio",
  "Business tools": "Mi negocio",
  "By end of December": "Para fin de diciembre",
  "By when — optional": "Para cuándo — opcional",
  "By when?": "¿Para cuándo?",
  "Can I afford $500 more this month?": "¿Me alcanza para gastar $500 más este mes?",
  "Cancel": "Cancelar",
  "Cancel {name}": "Cancelar {name}",
  "Cards and loans. I'll tell you exactly when each one dies. Skip if none.": "Tarjetas y préstamos. Te digo exactamente cuándo terminas de pagar cada uno. Sáltalo si no tienes.",
  "Cash": "Efectivo",
  "Cash on hand": "Efectivo disponible",
  "Category": "Categoría",
  "Check one off and your budget updates itself.": "Márcala como hecha y tu presupuesto se actualiza solo.",
  "Checking": "Cheques",
  "Clear": "Borrar",
  "Cleared {v0} — transactions and plans for that month are gone.": "Se borró {v0} — las transacciones y planes de ese mes ya no están.",
  "Close": "Cerrar",
  "Collapse {v0}": "Contraer {v0}",
  "Coming soon.": "Muy pronto.",
  "Compare": "Comparar",
  "Compare before you send": "Compara antes de enviar",
  "Complete {v0}": "Completar {v0}",
  "Confirm": "Confirmar",
  "Connect a bank": "Conectar un banco",
  "Connect your bank and transactions come in by themselves. Read-only — we can't move money.": "Conecta tu banco y las transacciones entran solas. Solo lectura — no podemos mover tu dinero.",
  "Connected. {n} transactions imported — more may arrive in a few minutes.": "Conectado. Se importaron {n} transacciones — pueden llegar más en unos minutos.",
  "Connecting and importing…": "Conectando e importando…",
  "Continue": "Continuar",
  "Contractors": "Contratistas",
  "Copy last month": "Copiar el mes pasado",
  "Could not switch. Try again.": "No se pudo cambiar. Intenta de nuevo.",
  "Could push:": "Se podría mover:",
  "Couldn't analyze right now. Try again.": "No pude analizar ahorita. Intenta de nuevo.",
  "Couldn't connect: {e}": "No se pudo conectar: {e}",
  "Couldn't create it — maybe that name already exists.": "No se pudo crear — tal vez ese nombre ya existe.",
  "Couldn't create that category — maybe the name already exists.": "No se pudo crear esa categoría — tal vez el nombre ya existe.",
  "Couldn't delete that category: {v0}": "No se pudo borrar esa categoría: {v0}",
  "Couldn't delete: {v0}": "No se pudo borrar: {v0}",
  "Couldn't load the overview. If this is new, the database update (migration 14) may still be pending.": "No se pudo cargar el resumen. Si esto es nuevo, puede faltar la actualización de la base de datos (migración 14).",
  "Couldn't record it. Try again.": "No se pudo registrar. Intenta de nuevo.",
  "Couldn't save.": "No se pudo guardar.",
  "Couldn't send that just now — try again.": "No se pudo enviar ahorita — intenta de nuevo.",
  "Couldn't start the bank connection.": "No se pudo iniciar la conexión con el banco.",
  "Counts in your monthly expense plan. Log each deposit with the + on the card.": "Cuenta en tu plan de gastos del mes. Registra cada depósito con el + de la tarjeta.",
  "Counts in your monthly income plan. Log each withdrawal with the − on the card.": "Cuenta en tu plan de ingresos del mes. Registra cada retiro con el − de la tarjeta.",
  "Create goal": "Crear meta",
  "Create task": "Crear tarea",
  "Credit": "Crédito",
  "Cumulative": "Acumulado",
  "Currency received": "Moneda que reciben",
  "Current balance": "Saldo actual",
  "Danger zone": "Zona de peligro",
  "Date": "Fecha",
  "Debt": "Deuda",
  "Debt-free by": "Sin deudas en",
  "Debts": "Deudas",
  "Delete": "Borrar",
  "Delete category": "Borrar categoría",
  "Delete task": "Borrar tarea",
  "Delete this entry": "Borrar este registro",
  "Delete this transfer and its expense?": "¿Borrar este envío y su gasto?",
  "Detection works from your transactions: write the merchant in the note (e.g. \"Netflix\") or use a Subscriptions category. Once your bank is connected, this fills in by itself.": "La detección usa tus transacciones: escribe el comercio en la nota (p. ej. \"Netflix\") o usa una categoría de Suscripciones. Cuando conectes tu banco, esto se llena solo.",
  "Disconnect": "Desconectar",
  "Disconnect this bank? Past transactions stay.": "¿Desconectar este banco? Las transacciones pasadas se quedan.",
  "Done — {amt} logged to {cat}. Budget updated.": "Listo — {amt} registrado en {cat}. Presupuesto actualizado.",
  "Done — {amt} logged. Budget updated.": "Listo — {amt} registrado. Presupuesto actualizado.",
  "Done — {amt} moved from Business to Personal.": "Listo — {amt} pasó de Negocio a Personal.",
  "Done ✓": "Hecho ✓",
  "Due date": "Fecha límite",
  "Due day {v0}": "Se paga el día {v0}",
  "Edit account": "Editar cuenta",
  "Edit budget — {v0}": "Editar presupuesto — {v0}",
  "Edit debt": "Editar deuda",
  "Edit entry": "Editar registro",
  "Edit goal": "Editar meta",
  "Edit investment": "Editar inversión",
  "Edit recurring item": "Editar recurrente",
  "Edit task": "Editar tarea",
  "Empty rows are skipped. Line items become plan amounts you fill up with the ✓ as money actually moves.": "Las filas vacías se ignoran. Las líneas se vuelven montos del plan que vas llenando con la ✓ conforme se mueve el dinero.",
  "Ends — optional": "Termina — opcional",
  "Enter an amount.": "Escribe un monto.",
  "Every 14 days — 26 payments a year, some months get 3": "Cada 14 días — 26 pagos al año, algunos meses tienen 3",
  "Every 2 weeks": "Cada 2 semanas",
  "Every 7 days": "Cada 7 días",
  "Every month": "Cada mes",
  "Every week": "Cada semana",
  "Every year": "Cada año",
  "Everyday spending (est.)": "Gasto diario (est.)",
  "Everything wiped — categories and accounts kept. Fresh start.": "Todo borrado — se quedaron las categorías y cuentas. Empiezas de cero.",
  "Exchange rate": "Tipo de cambio",
  "Expand {v0}": "Expandir {v0}",
  "Expected return %/yr": "Rendimiento esperado %/año",
  "Expense": "Gasto",
  "Expenses": "Gastos",
  "Fee": "Comisión",
  "Fees & bank charges": "Comisiones bancarias",
  "Fees this year": "Comisiones este año",
  "Finish": "Terminar",
  "Forecast": "Proyección",
  "Future month — left side is what's logged, right side is the plan.": "Mes futuro — a la izquierda lo registrado, a la derecha el plan.",
  "General": "General",
  "Get started": "Empezar",
  "Getting things ready…": "Preparando todo…",
  "Give it a name.": "Ponle un nombre.",
  "Give the new category a name.": "Ponle nombre a la nueva categoría.",
  "Go": "Ir",
  "Goal reached — {goal} sent this month.": "Meta cumplida — {goal} enviados este mes.",
  "Goals": "Metas",
  "Goals this month": "Metas este mes",
  "Got it — thank you. Tell us more anytime.": "Recibido — gracias. Cuéntanos más cuando quieras.",
  "Got it — thank you. That's exactly the kind of input that makes this better. Anything else? Ask me about your money or drop another idea.": "Recibido — gracias. Justo ese tipo de ideas hace esto mejor. ¿Algo más? Pregúntame sobre tu dinero o deja otra idea.",
  "Group them how you think — a category (Housing, Cars) and the lines inside it (Rent, insurance, tires). Add a few or skip.": "Agrúpalos como tú piensas — una categoría (Vivienda, Carros) y las líneas dentro (Renta, seguro, llantas). Agrega algunas o sáltalo.",
  "Heads up — red months ahead": "Ojo — vienen meses en rojo",
  "Hey": "Hola",
  "Hey, {name}": "Hola, {name}",
  "Hide breakdown ▴": "Ocultar desglose ▴",
  "Hide the math ▴": "Ocultar el cálculo ▴",
  "Hide what you don't use — bring it back anytime.": "Oculta lo que no usas — lo regresas cuando quieras.",
  "History": "Historial",
  "Home": "Inicio",
  "Home sections": "Secciones del inicio",
  "How much have I spent on Cars this year?": "¿Cuánto he gastado en carros este año?",
  "How much per month?": "¿Cuánto al mes?",
  "How much to set aside from each quarter's profit, and when it's due.": "Cuánto apartar de la ganancia de cada trimestre, y cuándo se paga.",
  "How's this figured? ▾": "¿Cómo se calcula? ▾",
  "I put money IN every month": "METO dinero cada mes",
  "I take money OUT every month": "SACO dinero cada mes",
  "In 12 months": "En 12 meses",
  "Income": "Ingresos",
  "Inside a group — optional": "Dentro de un grupo — opcional",
  "Insurance": "Seguros",
  "Interest left to pay": "Intereses por pagar",
  "Interest rate (APR %)": "Tasa de interés (APR %)",
  "Invested": "Invertido",
  "Invested today": "Invertido hoy",
  "Investments": "Inversiones",
  "Investments (est.)": "Inversiones (est.)",
  "Just log it": "Solo registrarlo",
  "Just this month": "Solo este mes",
  "Last year": "Año pasado",
  "Left": "Queda",
  "Live quotes from Wise's public comparison; totals can change at checkout. Some links may be affiliate links.": "Cotizaciones en vivo del comparador público de Wise; el total puede cambiar al pagar. Algunos enlaces pueden ser de afiliado.",
  "Live rates aren't available right now. Check these providers directly:": "Las tasas en vivo no están disponibles ahorita. Revisa estos proveedores directamente:",
  "Loading your month…": "Cargando tu mes…",
  "Loading…": "Cargando…",
  "Loan": "Préstamo",
  "Log a transfer": "Registrar un envío",
  "Logged once, just in this month.": "Se registra una vez, solo en este mes.",
  "Love that you want to help shape this. What would make Montfort Money better for you? Type it below and I'll pass it straight to the team.": "Qué bueno que quieras ayudar a darle forma. ¿Qué haría Montfort Money mejor para ti? Escríbelo abajo y se lo paso directo al equipo.",
  "Margin": "Margen",
  "Mark {v0} paid": "Marcar {v0} como pagado",
  "Marketing": "Marketing",
  "Minimize": "Minimizar",
  "Money": "Money",
  "Money dates": "Fechas de dinero",
  "Money tasks": "Tareas de dinero",
  "Montfort": "Montfort",
  "Montfort AI": "Montfort AI",
  "Montfort Money · early access. Tip: on iPhone, open this site in Safari and use Share → “Add to Home Screen” to install it like an app.": "Montfort Money · acceso anticipado. Tip: en iPhone, abre este sitio en Safari y usa Compartir → “Agregar a inicio” para instalarlo como app.",
  "Month": "Mes",
  "Month by month": "Mes por mes",
  "Monthly": "Mensual",
  "Monthly expenses": "Gastos mensuales",
  "Monthly goal": "Meta mensual",
  "Monthly income": "Ingreso mensual",
  "Monthly limit for": "Límite mensual para",
  "Monthly movement": "Movimiento mensual",
  "Monthly payment": "Pago mensual",
  "Monthly plan": "Plan mensual",
  "More": "Más",
  "Move money from the business to you. It's recorded as business spending and personal income in one step.": "Pasa dinero del negocio a ti. Se registra como gasto del negocio e ingreso personal en un solo paso.",
  "My business LLC": "Mi negocio LLC",
  "Name": "Nombre",
  "Name and current balance are required.": "Nombre y saldo actual son obligatorios.",
  "Name and target amount are required.": "Nombre y monto objetivo son obligatorios.",
  "Name, current balance and monthly payment are required.": "Nombre, saldo actual y pago mensual son obligatorios.",
  "Need the full history?": "¿Necesitas todo el historial?",
  "Needs {mo}/mo — ~{check} per paycheck for {n} more months": "Necesita {mo}/mes — ~{check} por cheque durante {n} meses más",
  "Net": "Neto",
  "Net in 12 months": "Neto en 12 meses",
  "Net this month": "Neto este mes",
  "Net this year": "Neto este año",
  "Net worth": "Patrimonio",
  "Net worth (tracked)": "Patrimonio (registrado)",
  "Net worth counts what you track here: investments + goal savings − debts. Transfers you pay yourself show as business spending and personal income.": "El patrimonio cuenta lo que registras aquí: inversiones + ahorro en metas − deudas. Lo que te pagas a ti mismo aparece como gasto del negocio e ingreso personal.",
  "New budget — {v0}": "Nuevo presupuesto — {v0}",
  "New connections go to your {space} space.": "Las nuevas conexiones van a tu espacio {space}.",
  "New expense category": "Nueva categoría de gasto",
  "New goal": "Nueva meta",
  "New income category": "Nueva categoría de ingreso",
  "New money task": "Nueva tarea de dinero",
  "New recurring expense": "Nuevo gasto recurrente",
  "New recurring income": "Nuevo ingreso recurrente",
  "Next 12 months": "Próximos 12 meses",
  "Next month": "Mes siguiente",
  "Next year": "Año siguiente",
  "No account": "Sin cuenta",
  "No budgets for {m} yet. Pick a category below to set your first limit — or copy last month's plan.": "Aún no hay presupuestos para {m}. Elige una categoría abajo para poner tu primer límite — o copia el plan del mes pasado.",
  "No debts tracked. Add them from your month page — balance, rate and payment — and this view shows exactly when each one dies.": "No tienes deudas registradas. Agrégalas desde tu mes — saldo, tasa y pago — y aquí verás exactamente cuándo terminas cada una.",
  "No expenses yet in this period.": "Aún no hay gastos en este periodo.",
  "No income yet in this period.": "Aún no hay ingresos en este periodo.",
  "No investments tracked. Add them from your month page and this view projects where each balance is heading.": "No tienes inversiones registradas. Agrégalas desde tu mes y aquí verás hacia dónde va cada saldo.",
  "No quotes for this amount.": "No hay cotizaciones para este monto.",
  "No tasks yet. Try “Pay credit card — $500, monthly” and watch it book itself when you complete it.": "Aún no hay tareas. Prueba “Pagar tarjeta — $500, mensual” y mira cómo se registra sola al completarla.",
  "No transactions in {m}.": "No hay transacciones en {m}.",
  "No transfers yet. Log one and it's added to your budget automatically.": "Aún no hay envíos. Registra uno y se suma a tu presupuesto automáticamente.",
  "Not budgeted yet": "Sin presupuesto aún",
  "Not in your plan": "No está en tu plan",
  "Note": "Nota",
  "Nothing recurring found yet.": "Aún no encontramos nada recurrente.",
  "Nothing recurring yet.": "Aún no hay nada recurrente.",
  "Nothing regular": "Nada fijo",
  "Nothing yet — tap ✓ when money moves.": "Nada aún — toca ✓ cuando se mueva el dinero.",
  "Now": "Ahora",
  "On the 15th and the 30th — 24 payments a year": "El 15 y el 30 — 24 pagos al año",
  "Once a month, same day": "Una vez al mes, el mismo día",
  "Once a year": "Una vez al año",
  "One-time": "Una sola vez",
  "Open": "Abrir",
  "Open Montfort AI": "Abrir Montfort AI",
  "Original total — optional": "Total original — opcional",
  "Other": "Otro",
  "Other income": "Otros ingresos",
  "Paid off in": "Pagada en",
  "Paid off in {v0} ({v1} payments) · ~{v2} in interest from here": "Pagada en {v0} ({v1} pagos) · ~{v2} de intereses desde hoy",
  "Paid to yourself this period: {amt} (not counted as an expense).": "Te pagaste en este periodo: {amt} (no cuenta como gasto).",
  "Pay myself": "Pagarme",
  "Pay yourself": "Págate a ti mismo",
  "Payment due day (1-31)": "Día de pago (1-31)",
  "Payment due day {v0}": "Día de pago {v0}",
  "Payment due day — optional": "Día de pago — opcional",
  "Per month": "Al mes",
  "Per year": "Al año",
  "Personal": "Personal",
  "Personal and business side by side — the full picture of your money.": "Personal y negocio lado a lado — la foto completa de tu dinero.",
  "Plan line items in": "Planea líneas en",
  "Plan through {v0}": "Plan hasta {v0}",
  "Plan · every 2 weeks": "Plan · cada 2 semanas",
  "Plan · monthly": "Plan · mensual",
  "Plan · this month": "Plan · este mes",
  "Plan · twice a month": "Plan · dos veces al mes",
  "Plan · weekly": "Plan · semanal",
  "Plan · yearly": "Plan · anual",
  "Planned end of month": "Plan a fin de mes",
  "Previous month": "Mes anterior",
  "Previous year": "Año anterior",
  "Price went up": "Subió de precio",
  "Privacy": "Privacidad",
  "Profit": "Ganancia",
  "Profit & loss": "Pérdidas y ganancias",
  "Profit & loss, quarterly taxes and paying yourself.": "Pérdidas y ganancias, impuestos trimestrales y pagarte a ti mismo.",
  "Projected income and expenses for the next 12 months": "Ingresos y gastos proyectados para los próximos 12 meses",
  "Provider": "Proveedor",
  "Putting in {v0}/mo (expense)": "Metiendo {v0}/mes (gasto)",
  "Quarterly estimated taxes": "Impuestos estimados trimestrales",
  "Quick add line item": "Agregar línea rápido",
  "Rate": "Tasa",
  "Recently completed": "Completadas recientemente",
  "Recipient": "Quién recibe",
  "Recurring": "Recurrentes",
  "Recurring charges found in your history — including the ones you forgot about.": "Cargos recurrentes en tu historial — incluso los que ya olvidaste.",
  "Recurring expenses": "Gastos recurrentes",
  "Recurring income": "Ingresos recurrentes",
  "Remind me to cancel": "Recordarme cancelar",
  "Reminder added to Tasks": "Recordatorio agregado a Tareas",
  "Remittances": "Remesas",
  "Remittances need a database update (migration 15). Run it in Supabase and reload.": "Remesas necesita una actualización de la base de datos (migración 15). Córrela en Supabase y recarga.",
  "Remove": "Quitar",
  "Remove budget": "Quitar presupuesto",
  "Remove category": "Quitar categoría",
  "Remove line": "Quitar línea",
  "Remove plan": "Quitar plan",
  "Rent & utilities": "Renta y servicios",
  "Rent, insurance, subscriptions, car payments…": "Renta, seguros, suscripciones, pagos del carro…",
  "Repeats": "Se repite",
  "Repeats?": "¿Se repite?",
  "Replay setup": "Repetir configuración",
  "Reset everything": "Borrar todo",
  "Safe to spend": "Puedes gastar",
  "Salary, bonuses, Montfort income, rents…": "Salario, bonos, ingresos de Montfort, rentas…",
  "Sales": "Ventas",
  "Save": "Guardar",
  "Save budget": "Guardar presupuesto",
  "Save changes": "Guardar cambios",
  "Save everything": "Guardar todo",
  "Save transfer": "Guardar envío",
  "Saved in goals": "Ahorrado en metas",
  "Saved.": "Guardado.",
  "Savings": "Ahorros",
  "Saving…": "Guardando…",
  "See the full forecast →": "Ver la proyección completa →",
  "Send": "Enviar",
  "Send suggestion": "Enviar sugerencia",
  "Sending…": "Enviando…",
  "Sent this year": "Enviado este año",
  "Services": "Servicios",
  "Set a goal (optional)": "Pon una meta (opcional)",
  "Set a monthly goal to track your sending.": "Pon una meta mensual para seguir tus envíos.",
  "Set this month's plan": "Poner el plan de este mes",
  "Share a suggestion →": "Compartir una sugerencia →",
  "Show as its own section": "Mostrar como sección propia",
  "Sign out": "Cerrar sesión",
  "Skip for now": "Saltar por ahora",
  "Skip setup": "Saltar configuración",
  "Skip this": "Saltar",
  "Software & tools": "Software y herramientas",
  "Something went wrong. Please try again.": "Algo salió mal. Intenta de nuevo.",
  "Sorry, I couldn't answer that.": "Perdón, no pude responder eso.",
  "Space": "Espacio",
  "Spending": "Gastos",
  "Spent": "Gastado",
  "Starts": "Empieza",
  "Statement close day": "Día de corte",
  "Statement close day — optional": "Día de corte — opcional",
  "Statement closes day {v0}": "Corte el día {v0}",
  "Stopped charging?": "¿Dejaron de cobrar?",
  "Subscriptions": "Suscripciones",
  "Suggested: keep {tax} for taxes; up to {pay} of this period's profit is left to pay yourself.": "Sugerido: aparta {tax} para impuestos; te quedan hasta {pay} de la ganancia de este periodo para pagarte.",
  "Suggestions": "Sugerencias",
  "Supplies & materials": "Insumos y materiales",
  "Switch to Business": "Cambiar a Negocio",
  "Switch to Business and the whole app — plan, recurring, goals, AI — works for your business, kept apart from your personal money.": "Cambia a Negocio y toda la app — plan, recurrentes, metas, IA — trabaja para tu negocio, separada de tu dinero personal.",
  "Sync failed.": "Falló la sincronización.",
  "Sync now": "Sincronizar",
  "Synced: {a} new, {u} updated.": "Sincronizado: {a} nuevas, {u} actualizadas.",
  "Taking out {v0}/mo (income)": "Sacando {v0}/mes (ingreso)",
  "Tap again to wipe it all": "Toca otra vez para borrar todo",
  "Tap again — removes the plan, keeps what you logged": "Toca otra vez — quita el plan, deja lo registrado",
  "Tap to edit what you logged": "Toca para editar lo registrado",
  "Target amount": "Monto objetivo",
  "Target reached — nice.": "Meta alcanzada — bien hecho.",
  "Target reached 🎯": "Meta alcanzada 🎯",
  "Tasks": "Tareas",
  "Taxes": "Impuestos",
  "Terms": "Términos",
  "These used to charge regularly but the last expected charge hasn't shown up.": "Estos cobraban seguido pero el último cargo esperado no ha llegado.",
  "They receive in": "Reciben en",
  "Thinking…": "Pensando…",
  "This month": "Este mes",
  "This month only": "Solo este mes",
  "This quarter": "Este trimestre",
  "To debt": "A deudas",
  "To goals": "A metas",
  "Toggle theme": "Cambiar tema",
  "Toggle {v0}": "Mostrar/ocultar {v0}",
  "Tools": "Herramientas",
  "Top level": "Nivel principal",
  "Total debt": "Deuda total",
  "Track brokerage, retirement, crypto or your house fund — and watch the balance grow with each contribution.": "Sigue tu bolsa, retiro, cripto o fondo para casa — y mira crecer el saldo con cada aporte.",
  "Track what you send home, and find the provider that delivers the most.": "Lleva cuenta de lo que mandas a casa y encuentra el proveedor que entrega más.",
  "Transaction": "Transacción",
  "Transfer": "Envío",
  "Twice a month": "Dos veces al mes",
  "Type": "Tipo",
  "Type your suggestion…": "Escribe tu sugerencia…",
  "Uncategorized": "Sin categoría",
  "Undo": "Deshacer",
  "Until — optional": "Hasta — opcional",
  "Up next": "Lo que sigue",
  "Utilities": "Servicios",
  "Vehicle & fuel": "Vehículo y gasolina",
  "We're building Montfort Money with you — got an idea or something that bugs you?": "Estamos construyendo Montfort Money contigo — ¿tienes una idea o algo que te moleste?",
  "We're building Montfort Money with you — this is the moment your ideas shape it most. What would make it better?": "Estamos construyendo Montfort Money contigo — este es el momento en que tus ideas más cuentan. ¿Qué lo haría mejor?",
  "Weekly": "Semanal",
  "Welcome": "Bienvenida",
  "What are you saving for?": "¿Para qué estás ahorrando?",
  "What kind of debt?": "¿Qué tipo de deuda?",
  "What needs to happen?": "¿Qué hay que hacer?",
  "Which bills are coming before my next paycheck?": "¿Qué cuentas vienen antes de mi próximo cheque?",
  "Wipes all transactions, plans, debts, investments, goals and tasks. Your categories, accounts and login stay. This can't be undone.": "Borra todas las transacciones, planes, deudas, inversiones, metas y tareas de este espacio. Tus categorías, cuentas y acceso se quedan. No se puede deshacer.",
  "Year to date": "En lo que va del año",
  "Year to date, net": "Neto en lo que va del año",
  "Yearly": "Anual",
  "You send (USD)": "Envías (USD)",
  "Your business gets its own space": "Tu negocio tiene su propio espacio",
  "Your expenses": "Tus gastos",
  "Your income": "Tus ingresos",
  "Your month": "Tu mes",
  "Your recurring money, projected over the next 12 months.": "Tu dinero recurrente, proyectado a 12 meses.",
  "across all debts, at current payments": "de todas las deudas, con los pagos actuales",
  "at each account's expected return": "al rendimiento esperado de cada cuenta",
  "balance": "saldo",
  "before any new contributions": "sin contar nuevos aportes",
  "before your next paycheck,": "antes de tu próximo cheque,",
  "contribution to {v0}": "aporte a {v0}",
  "day": "día",
  "due": "vence",
  "e.g. Amex Gold": "p. ej. Amex Gold",
  "e.g. Amex Gold, Mercedes loan": "p. ej. Amex Gold, préstamo del carro",
  "e.g. Charles Schwab": "p. ej. Charles Schwab",
  "e.g. Chase checking": "p. ej. Chase cheques",
  "e.g. Costco": "p. ej. Costco",
  "e.g. Fidelity brokerage, House fund": "p. ej. Fidelity, Fondo para casa",
  "e.g. House down payment": "p. ej. Enganche de la casa",
  "e.g. House down payment, Rolex, Japan trip": "p. ej. Enganche de la casa, Rolex, viaje a Japón",
  "e.g. Housing, Cars, Subscriptions": "p. ej. Vivienda, Carros, Suscripciones",
  "e.g. Housing, Vehicles, Subscriptions": "p. ej. Vivienda, Vehículos, Suscripciones",
  "e.g. IBM, My business, Rentals": "p. ej. Mi trabajo, Mi negocio, Rentas",
  "e.g. Mercedes": "p. ej. Carro",
  "e.g. Mom": "p. ej. Mamá",
  "e.g. My job, Rents, Montfort": "p. ej. Mi trabajo, Rentas, Montfort",
  "e.g. Netflix": "p. ej. Netflix",
  "e.g. Pay credit card": "p. ej. Pagar tarjeta",
  "e.g. Rent": "p. ej. Renta",
  "e.g. Rent, Netflix": "p. ej. Renta, Netflix",
  "e.g. Rents": "p. ej. Rentas",
  "e.g. Salary": "p. ej. Salario",
  "e.g. Salary, Bonus, PTO": "p. ej. Salario, Bono, PTO",
  "e.g. bonus": "p. ej. bono",
  "e.g. tires, insurance…": "p. ej. llantas, seguro…",
  "en-US": "es-US",
  "for the progress bar": "para la barra de progreso",
  "from your plan": "de tu plan",
  "general": "general",
  "last charged": "último cargo",
  "minutes": "minutos",
  "monthly": "mensual",
  "needs attention": "requiere atención",
  "never at this payment": "nunca con este pago",
  "next ~": "próximo ~",
  "of": "de",
  "optional": "opcional",
  "overdue — ": "vencida — ",
  "overdue — {v0}": "vencida — {v0}",
  "paid off {v0}": "pagada en {v0}",
  "pay": "pagar",
  "paying": "pagando",
  "payment doesn't cover interest": "el pago no cubre los intereses",
  "payment to {v0}": "pago a {v0}",
  "per year": "al año",
  "plan": "plan",
  "so far": "hasta ahora",
  "statement closes day {v0}": "corte el día {v0}",
  "synced": "sincronizado",
  "weekly": "semanal",
  "withdrawal from {v0}": "retiro de {v0}",
  "yearly": "anual",
  "{bal} now · ~{eoy} by Dec at {apr}%": "{bal} hoy · ~{eoy} para dic. al {apr}%",
  "{left} to go for your {goal} monthly goal.": "Faltan {left} para tu meta mensual de {goal}.",
  "{saved} of {target} · {pct}%": "{saved} de {target} · {pct}%",
  "{v0}/month — that's ~{v1} from each paycheck ({v2}) for {v3} months.": "{v0}/mes — son ~{v1} de cada cheque ({v2}) durante {v3} meses.",
  "~{eoy} by December · ~{in12} in 12 months at {apr}%/yr": "~{eoy} para diciembre · ~{in12} en 12 meses al {apr}%/año",
  "~{n} days": "~{n} días",
  "~{n}h": "~{n} h",
  "↗ own section": "↗ sección propia",
  "↙ Move back into": "↙ Regresar a",
  "⚠️ {amt}/mo doesn't cover interest at {apr}% — this one never dies. Raise the payment.": "⚠️ {amt}/mes no cubre los intereses al {apr}% — así nunca se termina. Sube el pago.",
  "⚠️ {v0}/mo doesn't cover the interest — this debt would never be paid off. Raise the payment.": "⚠️ {v0}/mes no cubre los intereses — esta deuda nunca se pagaría. Sube el pago.",
  "＋ New category…": "＋ Nueva categoría…",
  "Keep your business money apart from your personal money. Each space has its own plan, categories and history.": "Separa el dinero de tu negocio de tu dinero personal. Cada espacio tiene su propio plan, categorías e historial.",
  "Language": "Idioma",
  "{amt} planned": "{amt} planeado",
  "{amt} left": "quedan {amt}",
  "{pct}% paid off of {amt}": "{pct}% pagado de {amt}",
  "{pct}% paid off": "{pct}% pagado",
  "plan {amt}/mo": "plan {amt}/mes",
};
